### ISSUE TITLE
Error registración

### ISSUE THREAD

**Issue by jdromerorajoy** [eandreani/magento-2.2#1]
Hola!

Luego de instalar el modulo mediante composer, se genera un problema en la registración de clientes, para ser mas exacto en la ruta: /customer/account/createpost/

Tira lo siguiente:

![image](https://user-images.githubusercontent.com/18683388/42290475-d4ab3b30-7f9b-11e8-8e7d-c60a87e4d3a1.png)

Ya que esto se genera luego de instalar el modulo, me da a entender que es el atributo que agregan (DNI), lo que da el indicio que este sea el problema.

Ustedes lo han probado al módulo y les ha funcionado?
Necesitaria soporte urgente por favor.

Muchas gracias!

**Comment by Dvdam** [comment]
Tengo el mismo problema con Magento 2.2.5, al momento de crear una nueva cuenta de usuario la pagina queda en blanco y no me muestra ningún error por consola.

Necesito ayuda.

Muchas gracias

**Comment by carolinasolfernandez** [comment]
Buen día! Sigue sucediendo el problema?
