### ISSUE TITLE
Generación de guías errónea

### ISSUE THREAD

**Issue by iraima20** [eandreani/magento-2.2#2]
Versión de Magento 2.2.4

Cuando se generan las guías de forma masiva, se generan dos Números de Andreani diferentes en el mismo momento, en el admin de Magento aparece el segundo que se genera, pero el en el pdf aparce el primero. Por ejemplo - copio extracto del log:

2018-09-20T11:58:06+00:00 [NumeroAndreani] => 310000005751116 - Este es el que aparece en el pdf
2018-09-20T11:58:07+00:00 [NumeroAndreani] => 310000005751117 - Este es el que aparece en el admin y se envía al cliente por mail

El problema es que los clientes no pueden rastrear el pedido con el número que se les envía.

Lo esperado sería que genere un sólo número por envío y que aparezca tanto en el admin como en el PDF

**Comment by carolinasolfernandez** [comment]
Se solucionó:
[c905d12cf2adeed160632714cef6e8ae3f9bfc2a](https://github.com/eandreani/magento-2.2/commit/c905d12cf2adeed160632714cef6e8ae3f9bfc2a)

**Comment by iraima20** [comment]
> Se solucionó:
> [c905d12cf2adeed160632714cef6e8ae3f9bfc2a](https://github.com/eandreani/magento-2.2/commit/c905d12cf2adeed160632714cef6e8ae3f9bfc2a)

Hola @cafernandez

Con el arreglo, cuando genero la guía manda el mail al cliente sin el número de guía y tampoco se agrega en el admin en la parte de: Shipping and Tracking Information.

¿Pueden ver esto por favor?

Gracias

**Comment by carolinasolfernandez** [comment]
Iraima, podrías probar con este ultimo fix:
https://github.com/eandreani/magento-2.2/commit/0c059ca616eee87bcceb3946a2f9d9e1b0d015d2
?

**Comment by iraima20** [comment]
@cafernandez Gracias, con la última versión si funciona. 

Saludos
