### ISSUE TITLE
Retira en sucursal sin elegir sucursal

### ISSUE THREAD

**Issue by shipupi** [eandreani/magento-2.2#3]
Es posible (durante el checkout) elegir la opcion "retira en sucursal" pero despues no elegir la sucursal,

**Comment by iraima20** [comment]
Me pasa lo mismo, y cuando eso sucede el envío se procesa con precio $0 y además no es posible generar la guía de envío porque aparece el error FaultSinCodigo, porque no tiene el id de la sucural.

**Comment by carolinasolfernandez** [comment]
Fue solucionado en el commit [b83c4493fbda3d8b7132a4500dc9eea98c04dd71](https://github.com/eandreani/magento-2.2/commit/b83c4493fbda3d8b7132a4500dc9eea98c04dd71)
