### ISSUE TITLE
Limitar tamaños de campos para que se ajusten a los requisitos del webservice

### ISSUE THREAD

**Issue by iraima20** [eandreani/magento-2.2#5]
Hola, buenas tardes.

Estuve teniendo un error para generar guías para algunos pedidos. El error que me aparecía en el log no era específico, por lo que intenté mediante la consola de Andreani y me di cuenta de que me devolvía el mismo error. Contacté a webservicecasa@andreani.com y me comentaron que los campos <ns1:DetalleDeProductosAEntregar> y <ns1:DetalleDeProductosARetirar> aceptan un máximo de 100 caracteres y los datos de la orden tenían 106. **Lo ideal sería limitar lo que se le envía a Andreani a través de la API para que envíe hasta el máximo de caracteres aceptado por el webservice para cada campo y que genere la guía sin problemas**. Tengo el caso de dos clientes que están tratando de generar guías para órdenes de 6 productos y no pueden debido a esto.

Saludos

**Comment by carolinasolfernandez** [comment]
Solucionado en el commit:
https://github.com/eandreani/magento-2.2/commit/453d52c929b0edd4046ce413bf1be3a447aae9d4
